### ISSUE TITLE
cd doesn't work in directories more than one level

### ISSUE THREAD

**Issue by faheel** [faraazahmad/shellrb#5] opened 2017-05-06 15:49 UTC
When using the `cd` command, like
```
cd home/abc/def
```
it only changes the directory to home and doesn't go deeper.

**Comment by faraazahmad** [comment] 2017-05-08 10:21
I'm aware of this issue and am currently working on it. It can hopefully be fixed by passing a block to ```Dir.chdir```

**Comment by faraazahmad** [comment] 2017-05-08 18:33
Check the latest commit in the dev branch. you can ```cd``` into multiple directories. 
But you can go back only one directory. So the issue isn't completely fixed.

**Closed** 2017-08-05 09:11 UTC
Labels: bug, help wanted
